### ISSUE TITLE
Demo playback with `-playdemo` causes segfault

### ISSUE THREAD

**Issue by ranguli** [ranguli/mindoom#52]
Recording a demo with `-record` and then playing it back with `-playdemo` results in a segfault:

```
Thread 1 "mindoom" received signal SIGSEGV, Segmentation fault.
0x0000000000448349 in ST_updateWidgets ()
    at ../src/doom/st_stuff.c:812
812         if (weaponinfo[plyr->readyweapon].ammo == am_noammo)
(gdb) backtrace
#0  0x0000000000448349 in ST_updateWidgets ()
    at ../src/doom/st_stuff.c:812
#1  0x000000000044844b in ST_Ticker () at ../src/doom/st_stuff.c:872
#2  0x000000000042912d in G_Ticker () at ../src/doom/g_game.c:959
#3  0x0000000000408548 in TryRunTics () at ../src/d_loop.c:784
#4  0x0000000000423cbc in D_DoomLoop () at ../src/doom/d_main.c:462
#5  0x0000000000424b2f in D_DoomMain () at ../src/doom/d_main.c:1351
#6  0x0000000000404c2b in main (argc=<optimized out>, 
    argv=0x7fffffff3048) at ../src/i_main.c:71
```

**Comment by ranguli** [comment]
This includes the demo that plays in the background on the main menu. To reproduce, start the game, wait at the main menu for a few seconds (until the background demo begins).

```
Thread 1 "mindoom" received signal SIGSEGV, Segmentation fault.
0x0000000000424a6e in G_CheckSpot (playernum=playernum@entry=1, 
    mthing=mthing@entry=0x526aea <deathmatchstarts+10>)
    at ../src/doom/g_game.c:1074
1074                if (players[i].mo->x == mthing->x << FRACBITS &&
backtrace
#0  0x0000000000424a6e in G_CheckSpot (playernum=playernum@entry=1, 
    mthing=mthing@entry=0x526aea <deathmatchstarts+10>)
    at ../src/doom/g_game.c:1074
#1  0x0000000000424bd4 in G_DeathMatchSpawnPlayer (
    playernum=playernum@entry=1) at ../src/doom/g_game.c:1179
#2  0x0000000000439c47 in P_SetupLevel (episode=<optimized out>, 
    map=<optimized out>, playermask=playermask@entry=0, 
    skill=<optimized out>) at ../src/doom/p_setup.c:852
#3  0x0000000000424239 in G_DoLoadLevel ()
    at ../src/doom/g_game.c:607
#4  0x0000000000425549 in G_InitNew (skill=sk_nightmare, 
    skill@entry=109, episode=<optimized out>, episode@entry=3, 
    map=<optimized out>, map@entry=1) at ../src/doom/g_game.c:1646
#5  0x0000000000425ad8 in G_DoPlayDemo ()
    at ../src/doom/g_game.c:1892
#6  0x000000000042610d in G_Ticker () at ../src/doom/g_game.c:833
#7  0x00000000004084f8 in TryRunTics () at ../src/d_loop.c:774
#8  0x0000000000420f12 in D_RunFrame () at ../src/doom/d_main.c:386
#9  0x0000000000421047 in D_DoomLoop () at ../src/doom/d_main.c:439
#10 0x0000000000421a17 in D_DoomMain () at ../src/doom/d_main.c:1145
#11 0x0000000000404c0b in main (argc=<optimized out>, 
    argv=0x7fffffff3058) at ../src/i_main.c:71
```

We obviously broke something along the way in our various code removal crimes.

**Comment by ranguli** [comment]
This bug is not present in v0.0.3 and was introduced in v0.0.4.

**Comment by ranguli** [comment]
Demos are no longer segfaulting on playback (the scope of this issue). However are very desynced. See #57 and #56
